### ISSUE TITLE
Option not working??

### ISSUE THREAD

**Issue by gzz2000** [medikoo/bespoke-sync#2]
https://github.com/medikoo/bespoke-sync/blob/master/client/index.js#L7
https://github.com/medikoo/bespoke-sync/blob/master/client/sse.js#L9
https://github.com/medikoo/bespoke-sync/blob/master/client/xhr.js#L11

I need to specify ssePath, xhrPath but found that they are not working, after investigating the source I found that the option parameter of these files are commented out.
Is this deliberate or is it for debug purpose only but unexpectedly got uploaded to npm?

**Comment by medikoo** [comment]
@gzz2000 thanks for report.

They definitely should work, so if it doesn't work for you, I assume there's some issue in your setup.

They're not commented out. Comment just indicates that argument is optional (note it's written in ES5, so before ES6 gooddies were widely available)

**Comment by gzz2000** [comment]
Thank you for your response.
Perhaps I found the issue, 
https://github.com/medikoo/bespoke-sync/blob/master/client/index.js#L7
I think it should be changed to `arguments[0]`

**Comment by medikoo** [comment]
@gzz2000 indeed, well spotted!

Thanks for report. Fixed and published with v0.2.2
